name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Install wavesongs
        run: |
          pip install -e .

      - name: Sphinx build
        run: |
          sphinx-build docs _build

      - name: Push docs to external repository
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          cd _build
          git init
          git remote add origin https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/wavesongs/wavesongs.github.io.git
          git add .
          git commit -m "Update documentation from source repo 2"
          git push --force origin gh-pages
